# Generated by Django 6.0.2 on 2026-02-17 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_branch_options_alter_branch_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('student', 'Student Management'), ('academic', 'Academic Management'), ('attendance', 'Attendance Management'), ('finance', 'Finance Management'), ('exam', 'Exam & Result Management'), ('staff', 'Staff Management'), ('notification', 'Notification Management'), ('report', 'Report Generation'), ('system', 'System Administration'), ('branch', 'Branch Management')], default='system', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'code'],
                'indexes': [models.Index(fields=['code'], name='rbac_permis_code_f6107f_idx'), models.Index(fields=['category'], name='rbac_permis_categor_fa86d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('superadmin', 'Super Administrator'), ('principal', 'Principal'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('employee', 'Employee'), ('parent', 'Parent'), ('student', 'Student')], max_length=50)),
                ('display_name', models.CharField(help_text='Human-readable role name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('level_rank', models.PositiveSmallIntegerField(help_text='Lower number = higher authority (0–100)')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.schooltenant')),
            ],
            options={
                'ordering': ['level_rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='tenants.branch')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check', 'Permission Check'), ('grant', 'Permission Granted'), ('revoke', 'Permission Revoked'), ('deny', 'Permission Denied')], max_length=20)),
                ('permission_code', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('granted', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='rbac_permis_user_id_096453_idx'), models.Index(fields=['permission_code', 'granted'], name='rbac_permis_permiss_d5ac8a_idx'), models.Index(fields=['timestamp'], name='rbac_permis_timesta_3bec45_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'level_rank'], name='rbac_role_tenant__06b00c_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='rbac_role_name_92eec1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='rbac_rolepe_role_id_4acee1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='rbac_userro_user_id_78ba5c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'branch'], name='rbac_userro_role_id_05490b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['valid_from', 'valid_until'], name='rbac_userro_valid_f_65bba1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'branch')},
        ),
    ]
