# Generated by Django 6.0.2 on 2026-02-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0002_alter_branch_options_alter_branch_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, verbose_name='Fee Frequency')),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Required if frequency is monthly', max_digits=10, null=True, verbose_name='Monthly Fee (PKR)')),
                ('yearly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Required if frequency is yearly', max_digits=10, null=True, verbose_name='Yearly Fee (PKR)')),
                ('yearly_installments', models.PositiveIntegerField(blank=True, help_text='Required if frequency is yearly', null=True, verbose_name='No. of Installments per Year')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: yearly_amount / yearly_installments', max_digits=10, null=True, verbose_name='Each Installment Amount (PKR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.branch', verbose_name='Branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.schooltenant', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Branch Fee Structure',
                'verbose_name_plural': 'Branch Fee Structures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Scholarship Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('scholarship_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=15, verbose_name='Scholarship Type')),
                ('percentage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Required if type is percentage (e.g. 25 for 25%)', max_digits=5, null=True, verbose_name='Percentage (%)')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Required if type is fixed', max_digits=10, null=True, verbose_name='Fixed Amount (PKR)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scholarships', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='tenants.schooltenant', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Amount (PKR)')),
                ('scholarship_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Scholarship Deduction (PKR)')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Amount (PKR)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid (PKR)')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=10, verbose_name='Status')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('installment_number', models.PositiveIntegerField(blank=True, help_text='For yearly fee structures', null=True, verbose_name='Installment #')),
                ('label', models.CharField(blank=True, help_text="e.g. 'January 2026' or 'Installment 2 of 3'", max_length=255, verbose_name='Fee Label')),
                ('received_by_role', models.CharField(blank=True, max_length=30, verbose_name='Receiver Role')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_created', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
                ('fee_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees', to='finance.branchfeestructure', verbose_name='Fee Structure')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_received', to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='tenants.schooltenant', verbose_name='School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Fee',
                'verbose_name_plural': 'Student Fees',
                'ordering': ['-due_date', 'student__first_name'],
                'indexes': [models.Index(fields=['student', 'status'], name='finance_stu_student_7c0999_idx'), models.Index(fields=['branch', 'status'], name='finance_stu_branch__ca4a48_idx'), models.Index(fields=['due_date'], name='finance_stu_due_dat_e9a046_idx')],
            },
        ),
    ]
