# Generated by Django 6.0.2 on 2026-02-19 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='fee_type',
            field=models.CharField(choices=[('academic', 'Academic Fee'), ('special', 'Special Fee')], default='academic', max_length=10, verbose_name='Fee Type'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees', to='finance.branchfeestructure', verbose_name='Fee Structure'),
        ),
    ]
