# Generated by Django 6.0.2 on 2026-02-19 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_studentfee_fee_type_alter_studentfee_fee_structure'),
        ('tenants', '0003_branch_manager_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Expense Title')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('maintenance', 'Maintenance'), ('supplies', 'Supplies / Stationery'), ('transport', 'Transport'), ('furniture', 'Furniture'), ('events', 'Events'), ('other', 'Other')], max_length=30, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (PKR)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Expense Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.schooltenant', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'expense_date'], name='finance_exp_branch__a767bb_idx'), models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(blank=True, max_length=30, verbose_name='Employee Type')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary Amount (PKR)')),
                ('month', models.PositiveIntegerField(verbose_name='Month (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Notes / Description')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('paid_by_role', models.CharField(blank=True, max_length=30, verbose_name='Paid By Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_paid', to=settings.AUTH_USER_MODEL, verbose_name='Paid By')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='tenants.schooltenant', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Salary Record',
                'verbose_name_plural': 'Salary Records',
                'ordering': ['-year', '-month', 'employee__full_name'],
                'indexes': [models.Index(fields=['branch', 'month', 'year'], name='finance_sal_branch__e35f13_idx'), models.Index(fields=['status'], name='finance_sal_status_d7ed47_idx')],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
