# Generated by Django 6.0.2 on 2026-02-16 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('slug', models.SlugField(blank=True, help_text='URL identifier (auto-generated)', unique=True)),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('established_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Established Year')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='Registration Number')),
                ('is_active', models.BooleanField(default=True)),
                ('max_branches', models.IntegerField(default=5, help_text='Maximum branches allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_school', to=settings.AUTH_USER_MODEL, verbose_name='School Principal')),
            ],
            options={
                'verbose_name': 'School Tenant',
                'verbose_name_plural': 'School Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Branch Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('is_main_branch', models.BooleanField(default=False, help_text='Is this the main branch?')),
                ('is_active', models.BooleanField(default=True)),
                ('manager_temp_email', models.EmailField(blank=True, max_length=254, verbose_name='Manager Temporary Email')),
                ('manager_temp_password', models.CharField(blank=True, max_length=100, verbose_name='Manager Temporary Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to=settings.AUTH_USER_MODEL, verbose_name='Branch Manager')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.schooltenant', verbose_name='School')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'is_active'], name='tenants_bra_school__18466f_idx'), models.Index(fields=['manager'], name='tenants_bra_manager_f9408f_idx')],
            },
        ),
    ]
