# Generated by Django 6.0.2 on 2026-02-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['school', '-is_main_branch', 'name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('school', 'code')},
        ),
    ]
