# Generated by Django 6.0.2 on 2026-02-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_branch_options_alter_branch_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Manager Salary (PKR)'),
        ),
    ]
