# Generated by Django 6.0.2 on 2026-02-18 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0002_alter_branch_options_alter_branch_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Exam Name')),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('final', 'Final'), ('unit_test', 'Unit Test'), ('monthly_test', 'Monthly Test'), ('quarterly_test', 'Quarterly Test'), ('yearly_test', 'Yearly Test'), ('annual_test', 'Annual Test'), ('other', 'Other')], max_length=20, verbose_name='Exam Type')),
                ('date', models.DateField(verbose_name='Exam Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes', verbose_name='Duration (minutes)')),
                ('total_marks', models.PositiveIntegerField(default=100, verbose_name='Total Marks')),
                ('passing_marks', models.PositiveIntegerField(default=33, verbose_name='Passing Marks')),
                ('description', models.TextField(blank=True, verbose_name='Description / Instructions')),
                ('is_published', models.BooleanField(default=False, verbose_name='Results Published')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.branch', verbose_name='Branch')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.class', verbose_name='Class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.schooltenant', verbose_name='School')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.section', verbose_name='Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=10, verbose_name='Attendance Status')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='exams.exam', verbose_name='Exam')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_exam_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendance', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Exam Attendance',
                'verbose_name_plural': 'Exam Attendance',
                'ordering': ['student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Obtained Marks')),
                ('grade', models.CharField(blank=True, max_length=5, verbose_name='Grade')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('is_absent', models.BooleanField(default=False, verbose_name='Absent (no marks)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['student__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date', 'section'], name='exams_exam_date_d33cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['branch', 'is_active'], name='exams_exam_branch__3efc86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattendance',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
    ]
