# Generated by Django 6.0.2 on 2026-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups exams created together across multiple sections', null=True, verbose_name='Batch ID'),
        ),
    ]
