# Generated by Django 6.0.2 on 2026-02-18 20:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0002_alter_branch_options_alter_branch_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Qualification')),
                ('certification', models.CharField(blank=True, max_length=200, verbose_name='Certification')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Employee Code')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, verbose_name='Joining Date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountants', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accountants', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountants', to='tenants.schooltenant', verbose_name='School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accountant',
                'verbose_name_plural': 'Accountants',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Qualification')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Employee Code')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, verbose_name='Joining Date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teachers', to=settings.AUTH_USER_MODEL)),
                ('incharge_section', models.ForeignKey(blank=True, help_text='Section this teacher is incharge of (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_teacher', to='academics.section', verbose_name='Incharge of Section')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='tenants.schooltenant', verbose_name='School')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subjects this teacher teaches', related_name='teachers', to='academics.subject', verbose_name='Subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name="Father's Name")),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Alternate Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('employee_type', models.CharField(choices=[('guard', 'Guard'), ('clerk', 'Clerk'), ('cleaner', 'Cleaner'), ('driver', 'Driver'), ('other', 'Other')], max_length=20, verbose_name='Employee Type')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Qualification')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Employee Code')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, verbose_name='Joining Date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profiles/', verbose_name='Profile Picture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('cnic', models.CharField(blank=True, help_text='Format: 12345-1234567-1', max_length=15, verbose_name='CNIC Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants.schooltenant', verbose_name='School')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['employee_id'], name='staff_emplo_employe_4a1a40_idx'), models.Index(fields=['employee_type'], name='staff_emplo_employe_961d6a_idx'), models.Index(fields=['branch', 'is_active'], name='staff_emplo_branch__2129ba_idx')],
            },
        ),
    ]
