# Generated by Django 6.0.2 on 2026-02-18 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0002_alter_branch_options_alter_branch_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'Leave'), ('halfleave', 'Half Leave')], default='present', max_length=10, verbose_name='Status')),
                ('late_time', models.TimeField(blank=True, help_text='The time the staff member arrived (if late)', null=True, verbose_name='Late Arrival Time')),
                ('half_leave_time', models.TimeField(blank=True, help_text='The time the staff member left on half leave', null=True, verbose_name='Half Leave Time')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='tenants.branch', verbose_name='Branch')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='tenants.schooltenant', verbose_name='School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Staff User')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance',
                'ordering': ['-date', 'user__full_name'],
                'indexes': [models.Index(fields=['date', 'branch'], name='attendance__date_cb90d9_idx'), models.Index(fields=['user', 'date'], name='attendance__user_id_7608a6_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'Leave'), ('halfleave', 'Half Leave')], default='present', max_length=10, verbose_name='Status')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='tenants.branch', verbose_name='Branch')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendance', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='tenants.schooltenant', verbose_name='School')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='academics.section', verbose_name='Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance',
                'ordering': ['-date', 'student__first_name'],
                'indexes': [models.Index(fields=['date', 'section'], name='attendance__date_d889f3_idx'), models.Index(fields=['student', 'date'], name='attendance__student_0335ea_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
