# Generated by Django 6.0.2 on 2026-02-19 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_scholarship'),
        ('tenants', '0003_branch_manager_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('character', 'Character Certificate'), ('bonafide', 'Bonafide Certificate'), ('fee_clearance', 'Fee Clearance Certificate'), ('result', 'Result Certificate'), ('leaving', 'Leaving Certificate'), ('experience', 'Experience Certificate (Employee)')], max_length=30, verbose_name='Certificate Type')),
                ('body_template', models.TextField(help_text='Use placeholders: {{student_name}}, {{class}}, {{section}}, {{admission_number}}, {{father_name}}, {{date}}, {{school_name}}, {{branch_name}}, etc. For experience: {{employee_name}}, {{designation}}, {{joining_date}}, {{leaving_date}}, etc.', verbose_name='Body Template (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='tenants.branch', verbose_name='Branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='tenants.schooltenant', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'ordering': ['template_type', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Serial Number')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='Generated PDF')),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Stored placeholder values used for this certificate', verbose_name='Certificate Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tenants.branch', verbose_name='Branch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Employee (for experience cert)')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tenants.schooltenant', verbose_name='School')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student', verbose_name='Student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificate.certificatetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'issued_date'], name='certificate_branch__bf9f8d_idx'), models.Index(fields=['serial_number'], name='certificate_serial__c3bb80_idx')],
            },
        ),
    ]
