# Generated by Django 6.0.2 on 2026-02-17 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_branch_options_alter_branch_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Class Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Class Code')),
                ('numeric_level', models.PositiveSmallIntegerField(blank=True, help_text='e.g., 1 for Grade 1, 2 for Grade 2', null=True, verbose_name='Numeric Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['numeric_level', 'name'],
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Section Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Section Code')),
                ('capacity', models.PositiveSmallIntegerField(default=30, help_text='Maximum number of students', verbose_name='Student Capacity')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Room Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.class', verbose_name='Class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['class_obj__numeric_level', 'name'],
                'unique_together': {('name', 'class_obj')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Subject Code')),
                ('subject_type', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective'), ('language', 'Language'), ('science', 'Science'), ('arts', 'Arts'), ('sports', 'Sports')], default='core', max_length=20, verbose_name='Subject Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('total_marks', models.PositiveSmallIntegerField(default=100, help_text='Maximum marks for this subject', verbose_name='Total Marks')),
                ('pass_marks', models.PositiveSmallIntegerField(default=33, help_text='Minimum marks required to pass', verbose_name='Passing Marks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Is Optional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
                'unique_together': {('code', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.section')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher assigned to teach this subject in this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Section Subject Assignment',
                'verbose_name_plural': 'Section Subject Assignments',
                'ordering': ['section', 'subject__name'],
                'unique_together': {('section', 'subject')},
            },
        ),
    ]
